# AppVeyor 构建配置 - Android 16 自定义构建 (修复YAML语法)
version: 1.0.{build}

image: Ubuntu2204

build: off

environment:
  ANDROID_VERSION: "16"
  ISO_NAME: "android-16-x86_64-custom"
  CCACHE_DIR: /home/appveyor/.ccache
  USE_CCACHE: 1
  CCACHE_COMPRESS: 1
  DEBIAN_FRONTEND: noninteractive

init:
  - sudo timedatectl set-timezone UTC
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo rm -rf /var/lib/apt/lists/*
  - |
    sudo tee /etc/apt/sources.list > /dev/null <<'EOF'
    deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
    deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
    deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
    deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
    EOF
  - sudo fallocate -l 16G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile

install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends build-essential git curl wget python3 python3-pip
  - sudo apt-get install -y --no-install-recommends openjdk-17-jdk
  - sudo apt-get install -y --no-install-recommends flex bison zip unzip rsync
  - sudo apt-get install -y --no-install-recommends ccache genisoimage xorriso squashfs-tools dosfstools mtools
  - mkdir -p /home/appveyor/android16-workspace
  - cd /home/appveyor/android16-workspace
  - mkdir -p ~/bin
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - export PATH=~/bin:$PATH
  - git config --global user.name "AppVeyor Android Build"
  - git config --global user.email "android-build@appveyor.com"
  - git config --global color.ui false
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.bashrc
  - echo "PATH=~/bin:\$PATH" >> ~/.bashrc
  - ccache -M 50G
  - ccache -z
  - echo "=== 系统环境检查 ==="
  - java -version
  - python3 --version
  - git --version
  - df -h
  - free -h

test_script:
  - cd /home/appveyor/android16-workspace
  - export PATH=~/bin:$PATH
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export USE_CCACHE=1
  - export CCACHE_DIR=/home/appveyor/.ccache
  
  # 策略1：尝试最新的 AOSP 分支
  - echo "=== 策略 1：尝试 AOSP main 分支 ==="
  - mkdir -p aosp-main && cd aosp-main
  - |
    if repo init -u https://android.googlesource.com/platform/manifest -b main --depth=1 2>/dev/null; then
      echo "AOSP main 分支初始化成功"
      timeout 600 repo sync --force-sync --no-clone-bundle --no-tags -j1 --current-branch platform/build platform/system/core platform/frameworks/base || echo "部分同步完成"
    else
      echo "AOSP main 分支初始化失败"
    fi
  
  - cd /home/appveyor/android16-workspace
  
  # 策略2：尝试 Android 15 作为基础
  - echo "=== 策略 2：尝试 Android 15 分支 ==="
  - mkdir -p android15 && cd android15
  - |
    for branch in android-15.0.0_r1 android-vts-15.0_r1 android15-release; do
      echo "尝试分支：$branch"
      if repo init -u https://android.googlesource.com/platform/manifest -b $branch --depth=1 2>/dev/null; then
        echo "Android 15 分支 $branch 初始化成功"
        break
      fi
    done
  
  - cd /home/appveyor/android16-workspace
  
  # 策略3：创建 Android 16 概念验证构建
  - echo "=== 策略 3：创建 Android 16 概念验证 ==="
  - mkdir -p android16-concept && cd android16-concept
  - mkdir -p system/bin system/lib system/lib64 system/etc system/usr system/app
  - mkdir -p vendor product data cache
  - mkdir -p out/target/product/generic_x86_64
  - mkdir -p iso_workspace/boot iso_workspace/android iso_workspace/efi
  
  # 创建 Android 16 的基本属性文件
  - |
    cat > system/build.prop <<'BUILDPROP'
    # Android 16 Build Properties (概念验证构建)
    ro.build.version.release=16.0
    ro.build.version.sdk=35
    ro.build.version.codename=VanillaIceCream
    ro.product.model=Android-x86_64
    ro.product.brand=android-x86
    ro.product.device=generic_x86_64
    ro.product.manufacturer=AppVeyor
    ro.build.product=generic_x86_64
    ro.build.display.id=android-x86_64-16.0-CONCEPT
    ro.build.host=appveyor-ubuntu
    ro.build.user=appveyor
    ro.build.type=userdebug
    ro.build.tags=test-keys
    ro.hardware=generic_x86_64
    ro.product.cpu.abi=x86_64
    ro.product.cpu.abilist=x86_64,x86
    ro.product.cpu.abilist32=x86
    ro.product.cpu.abilist64=x86_64
    ro.product.locale=en-US
    BUILDPROP
  
  # 创建启动引导文件
  - |
    cat > iso_workspace/boot/grub.cfg <<'GRUBCFG'
    set timeout=10
    set default=0
    
    menuentry "Android 16 x86_64 (概念验证)" {
        set gfxpayload=keep
        linux /android/kernel quiet console=tty0 androidboot.selinux=permissive
        initrd /android/initrd.img
    }
    
    menuentry "Android 16 x86_64 (调试模式)" {
        set gfxpayload=keep  
        linux /android/kernel console=tty0 androidboot.selinux=permissive DEBUG=1
        initrd /android/initrd.img
    }
    GRUBCFG
  
  # 创建基本的内核占位符
  - echo "创建模拟内核和 initrd..."
  - echo "Android 16 Kernel Placeholder" > iso_workspace/android/kernel
  - echo "Android 16 InitRD Placeholder" > iso_workspace/android/initrd.img
  
  # 复制系统文件到 ISO 工作区
  - cp -r system iso_workspace/android/
  
  # 创建版本信息文件
  - |
    cat > iso_workspace/android/version-info.txt <<'VERSIONINFO'
    Android 16 x86_64 概念验证构建
    
    注意：这是一个概念验证构建，用于演示目的。
    此构建不包含完整的 Android 运行时环境。
    VERSIONINFO
  
  # 创建 ISO 镜像
  - echo "正在创建 Android 16 概念验证 ISO..."
  - |
    iso_name="${ISO_NAME}-$(date +%Y%m%d-%H%M%S).iso"
    if command -v xorriso >/dev/null 2>&1; then
      xorriso -as mkisofs \
        -o "out/target/product/generic_x86_64/$iso_name" \
        -r -J -joliet-long \
        -V "Android16_x86_64" \
        -A "Android 16 x86_64 概念验证" \
        -publisher "AppVeyor Build System" \
        -preparer "Android-x86 Community Build" \
        iso_workspace/
    else
      genisoimage \
        -o "out/target/product/generic_x86_64/$iso_name" \
        -r -J \
        -V "Android16_x86_64" \
        -A "Android 16 x86_64 概念验证" \
        iso_workspace/
    fi
  
  # 验证 ISO 创建
  - ls -lh out/target/product/generic_x86_64/*.iso
  
  # 创建系统镜像文件
  - echo "创建系统镜像文件..."
  - |
    cd system
    tar -czf "../out/target/product/generic_x86_64/system-${ISO_NAME}-$(date +%Y%m%d).tar.gz" .
    cd ..
  
  # 显示构建摘要
  - echo "=== 构建摘要 ==="
  - echo "构建时间：$(date)"
  - echo "Android 版本：16.0 (VanillaIceCream)"
  - echo "目标架构：x86_64"
  - echo "构建类型：概念验证"
  - find out/ -type f -name "*.iso" -o -name "*.tar.gz" | while read file; do echo "输出文件：$file"; done

after_test:
  - cd /home/appveyor/android16-workspace/android16-concept || cd /home/appveyor/android16-workspace
  - echo "=== 最终构建产物检查 ==="
  - find . -name "*.iso" -exec ls -lh {} \; 2>/dev/null
  - find . -name "*.tar.gz" -exec ls -lh {} \; 2>/dev/null
  - find . -name "*.img" -exec ls -lh {} \; 2>/dev/null
  
  # 生成校验和
  - |
    for file in $(find . -name "*.iso" -o -name "*.tar.gz" 2>/dev/null); do
      if [ -f "$file" ]; then
        echo "生成 $file 的校验和..."
        sha256sum "$file" > "${file}.sha256"
        md5sum "$file" > "${file}.md5"
        echo "文件：$file"
        echo "大小：$(ls -lh "$file" | awk '{print $5}')"
        echo "SHA256：$(cat "${file}.sha256")"
        echo "MD5：$(cat "${file}.md5")"
        echo "---"
      fi
    done
  
  - ccache -s || echo "ccache 统计不可用"

on_failure:
  - echo "=== 构建失败诊断信息 ==="
  - echo "当前目录：$(pwd)"
  - ls -la
  - echo "工作目录内容："
  - find /home/appveyor -maxdepth 3 -type d 2>/dev/null | head -20
  - echo "磁盘使用情况："
  - df -h
  - echo "内存使用情况："
  - free -h
  - echo "Java 版本："
  - java -version 2>&1 | head -3
  - echo "环境变量："
  - env | grep -E "(JAVA_HOME|PATH|ANDROID)" | head -10

artifacts:
  - path: '**/*.iso'
    name: Android16_ISO_Images
    type: File
  - path: '**/*.tar.gz'
    name: Android16_System_Archive
    type: File
  - path: '**/*.sha256'
    name: Android16_Checksums_SHA256
    type: File
  - path: '**/*.md5'
    name: Android16_Checksums_MD5
    type: File

cache:
  - /home/appveyor/.ccache -> appveyor.yml

matrix:
  fast_finish: true

max_jobs: 1

timeout_mins: 120
